### PR TITLE
[Feat] Guide improvements / fixing wiki

### PR DESCRIPTION
**Pull request by ghost**
**Major Changes:**
- I went through the entire guide and rephrased a lot of my own broken English. It should be a little better now, or at least a little more formal and to the point. 
- I changed a lot of GIFs and images to reflect the use of mod manager. Previously, I simply re-used the same MO2 images and GIFs for various Vortex-related tasks; these have all been replaced. I don't think I missed any.
- Since the server guide section was created in a rush, it has been cleaned up. This includes updating the guide's images and GIFs. 

**Minor Changes:**
- Added a "index"-style page to the troubleshooting page, so it will have a list of the current pages in the troubleshooting "section."
- I alphabetized the pages in the troubleshooting sections
- Renamed/reworded the anniversary upgrade removal pages, and added a small information box about the v1.6 update and the (infamous) four CC items that must be removed.
- Included a more detailed explanation of what happened with the anniversary upgrade dlc situation.
- Modified the AES-NI troubleshooting page slightly so that it begins with an explanation of why AES-NI support is required in the first place.
- Added a link to the AES-NI to the client setup's 'Prerequisites' page, so people can see if their CPU supports it before going through the entire installation guide.
- The "My firewall didn't pop up page" was moved to the troubleshooting section, and links to it were added to the server guide itself.
- An uninstallation page with instructions for removing the mod from MO2 and VMM.
- Minor changes to the FAQ page. I hope that's OK. Mostly letter capitalization and minor sentence changes.
- I also added a small link to the troubleshooting page in the hopes that it will relieve some of the strain on the Discord help channels.
- Corrected the information on the "my game runs like shit" troubleshooting page. It made it much clearer on what to do. 

**Live Preview**: 
As always, you can see the changes here:
https://vp-en.gitbook.io/skyrimtogether/

### CODE REVIEW

**Comment by Dragonissa** [comment]
There is **no Anniversary Edition**. There was an Anniversary **Update** that came with 4 Mods and there is an Anniversary **Upgrade** which comes with countless of CC Mods.

**Comment by ghost** [comment]
> There is **no Anniversary Edition**. There was an Anniversary **Update** that came with 4 Mods and there is an Anniversary **Upgrade** which comes with countless of CC Mods.

Will fix that as well, thanks for clarifying 👍

**Comment by vp-en** [comment]
Ready for review. I think it's as good as it gets.

**Live preview available here:**
https://vp-en.gitbook.io/skyrimtogether/

**Comment by ghost** [comment]
Converting this back to draft, as Gitbook is acting weird. Going through the entire thing once more, and checking for small mistakes.

**Comment by ghost** [comment]
There we go!
Ready for review / ready for merging.

**Pull request merged**
